project:
  type: website

website:
  title: "Cynthia Garcia"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Marketing Analytics
        href: marketing-analytics.qmd
      - text: Digital Marketing
        href: digital-marketing.qmd
      - text: Resume
        href: resume.qmd

format:
  html:
    theme: minty
    toc: true

output-dir: docs
